version: 0.1
name: twitter-polarity

phases:
  pre_build:
    commands:
      - npm install

  build:
    commands:
      - npm run build
post_build:
    commands:

artifacts:
  files:
    - dist/*
    - index.html
